Controllers/ExpenseController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ExpenseTrack.Data;
using ExpenseTrack.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using ExpenseTrack.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;

namespace ExpenseTrack.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ExpenseTrackContext _context;

        public ExpenseController(ExpenseTrackContext context)
        {
            _context = context;
        }

        // GET: Expense
        public IActionResult Index(DateTime? filterDate, int page = 1, int pageSize = 5)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var expensesQuery = _context.Expenses
                    .Where(e => e.UserId == userId);

                if (filterDate.HasValue)
                {
                    expensesQuery = expensesQuery
                        .Where(e => e.Date.Date == filterDate.Value.Date);
                }

                var totalExpenses = expensesQuery.Count();
                var expenses = expensesQuery
                    .OrderByDescending(e => e.Date) 
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();

                var paginationModel = new PaginationModel<Expense>
                {
                    Items = expenses,
                    TotalItems = totalExpenses,
                    CurrentPage = page,
                    PageSize = pageSize
                };

                return View("Index", paginationModel); 
            }
            catch (Exception ex)
            {
                // Handle exception...
                return BadRequest("An error occurred while processing your request.");
            }
        }





        public IActionResult AddPage()
        {
            var categories = new List<string> { "Housing", "Transportation", "Entertainment", "Health and Wellbeing", "Debt Payments" , "Other" }; // Add your hardcoded categories
            ViewBag.Categories = categories.Select(c => new SelectListItem
            {
                Value = c,
                Text = c
            }).ToList();

            return View("Add");
        }
        [HttpPost]
        public IActionResult AddExpense(Expense expense)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                expense.UserId = userId;

                var user = _context.Users.FirstOrDefault(u => u.Id == userId);
                // bool addToWishlist = HttpContext.Request.Form["addToWishlist"] == "true";
                //System.Diagnostics.Debug.WriteLine($"addToWishlist: {addToWishlist}");

                if (user != null)
                {
                    if (expense.Amount > user.Balance)
                    {
                        // Expense amount exceeds user's balance
                        ViewBag.ExceedsBalance = true;
                        var categories = new List<string> { "Housing", "Transportation", "Entertainment", "Health and Wellbeing", "Debt Payments", "Other" }; // Add your hardcoded categories
                        ViewBag.Categories = categories.Select(c => new SelectListItem
                        {
                            Value = c,
                            Text = c
                        }).ToList();
                        return View("Add", new Expense());
                    }

                    else
                    {
                        // Deduct the amount from the user's balance
                        user.Balance -= expense.Amount;
                        _context.SaveChanges();

                        // Continue with the original logic
                        _context.Expenses.Add(expense);
                        _context.SaveChanges();

                        return RedirectToAction("Index");
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Log the exception or handle it as appropriate for your application
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
                var categories = new List<string> { "Housing", "Transportation", "Entertainment", "Health and Wellbeing", "Debt Payments", "Other" }; // Add your hardcoded categories
                ViewBag.Categories = categories.Select(c => new SelectListItem
                {
                    Value = c,
                    Text = c
                }).ToList();
                return View("Add", expense);
            }
        }
        public IActionResult AddToWishlist(Expense expense)
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var wishlistItem = new WishlistItem
            {
                ExpenseName = expense.ExpenseName,
                Amount = expense.Amount,
                Date = expense.Date,
                Description = expense.Description,
                Category = expense.Category,
                UserId = userId
            };
            _context.WishlistItems.Add(wishlistItem);
            _context.SaveChanges();
            return RedirectToAction("Index");


        }




        public IActionResult EditPage(int ExpenseID)
        {
            var expense = _context.Expenses.FirstOrDefault(e => e.ExpenseID == ExpenseID);

            if (expense == null)
            {
                return NotFound();
            }
            var categories = new List<string> { "Housing", "Transportation", "Entertainment", "Health and Wellbeing", "Debt Payments", "Other" }; // Add your hardcoded categories
            ViewBag.Categories = categories.Select(c => new SelectListItem
            {
                Value = c,
                Text = c
            }).ToList();

            return View("Edit", expense);
        }


        [HttpPost]
        public IActionResult EditExpense(Expense updatedExpense)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            updatedExpense.UserId = userId;
            var user = _context.Users.FirstOrDefault(u => u.Id == userId);
            var originalExpense = _context.Expenses.AsNoTracking().FirstOrDefault(e => e.ExpenseID == updatedExpense.ExpenseID);
            user.Balance += originalExpense.Amount;

            if (updatedExpense.Amount > user.Balance)
            {
                // Expense amount exceeds user's balance
                ViewBag.ExceedsBalance = true;
                var categories = new List<string> { "Housing", "Transportation", "Entertainment", "Health and Wellbeing", "Debt Payments", "Other" }; // Add your hardcoded categories
                ViewBag.Categories = categories.Select(c => new SelectListItem
                {
                    Value = c,
                    Text = c
                }).ToList();
                return View("Edit", new Expense());
            }

            // Retrieve the original expense from the database

            // Adjust the user's balance

            user.Balance -= updatedExpense.Amount;

            // Update the expense in the database
            _context.Update(updatedExpense);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteExpense(int ExpenseID)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var expense = _context.Expenses.FirstOrDefault(e => e.ExpenseID == ExpenseID && e.UserId == userId);

            if (expense != null)
            {
                _context.Expenses.Remove(expense);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

    }
   

}


//public IActionResult ExpensePartialView(DateTime? filterDate)
//{
//    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
//    var expenses = _context.Expenses
//        .Include(e => e.Category)
//        .Where(e => e.UserId == userId)
//        .ToList();

//    if (filterDate.HasValue)
//    {
//        expenses = expenses.Where(e => e.Date.Date == filterDate.Value.Date).ToList();
//    }

//    return PartialView("_ExpenseIndexPartial", expenses);
//}

Controllers/Wishlist/WishlistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTrack.Data;
using ExpenseTrack.Models;
using System.Security.Claims;

public class WishlistController : Controller
{
    private readonly ExpenseTrackContext _context;

    public WishlistController(ExpenseTrackContext context)
    {
        _context = context;
    }

    public IActionResult Index(DateTime? filterDate, int page = 1, int pageSize = 5)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var wishlistItemsQuery = _context.WishlistItems
            .Where(w => w.UserId == userId);

        if (filterDate.HasValue)
        {
            wishlistItemsQuery = wishlistItemsQuery
                .Where(w => w.Date.Date == filterDate.Value.Date);
        }
        var userBalance = GetUserBalance(userId);
        ViewBag.UserBalance = userBalance;


        var totalWishlistItems = wishlistItemsQuery.Count();
        var wishlistItems = wishlistItemsQuery
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToList();

        var paginationModel = new PaginationModel<WishlistItem>
        {
            Items = wishlistItems,
            TotalItems = totalWishlistItems,
            CurrentPage = page,
            PageSize = pageSize
        };

        return View("WishlistIndex", paginationModel);
    }



    public IActionResult AddPage()

    {
        var categories = new List<string> { "Housing", "Transportation", "Entertainment", "Health and Wellbeing", "Debt Payments", "Other" }; // Add your hardcoded categories
        ViewBag.Categories = categories.Select(c => new SelectListItem
        {
            Value = c,
            Text = c
        }).ToList();
        return View("WishlistAdd");
    }

    [HttpPost]
    public IActionResult AddWishlistItem(WishlistItem wishlistItem)
    {
        try
        {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                wishlistItem.UserId = userId;

                // Add the wishlist item
                _context.WishlistItems.Add(wishlistItem);
                _context.SaveChanges();

                return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
            var categories = new List<string> { "Housing", "Transportation", "Entertainment", "Health and Wellbeing", "Debt Payments", "Other" }; // Add your hardcoded categories
            ViewBag.Categories = categories.Select(c => new SelectListItem
            {
                Value = c,
                Text = c
            }).ToList();
            return View("WishlistAdd", wishlistItem);
        }
    }

    [HttpPost]
    public IActionResult AddToExpense(int wishlistItemId)
    {
        try
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get the wishlist item
            var wishlistItem = _context.WishlistItems.FirstOrDefault(w => w.WishlistItemId == wishlistItemId && w.UserId == userId);

            if (wishlistItem != null)
            {
                // Check if the user balance is sufficient
                var user = _context.Users.FirstOrDefault(u => u.Id == userId);

                if (user != null && wishlistItem.Amount <= user.Balance)
                {
                    // Deduct the amount from the user's balance
                    user.Balance -= wishlistItem.Amount;
                    _context.SaveChanges();

                    // Add the item to expenses
                    var expense = new Expense
                    {
                        ExpenseName = wishlistItem.ExpenseName,
                        Amount = wishlistItem.Amount,
                        Date = wishlistItem.Date,
                        Description = wishlistItem.Description,
                        Category = wishlistItem.Category,
                        UserId = userId
                    };

                    _context.Expenses.Add(expense);
                    _context.SaveChanges();

                    // Remove the item from the wishlist
                    _context.WishlistItems.Remove(wishlistItem);
                    _context.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
        }
        catch (Exception ex)
        {
            // Log the exception or handle it as appropriate for your application
            return BadRequest("An error occurred while processing your request.");
        }

        // Redirect back to the wishlist if the operation is not successful
        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult DeleteWishlistItem(int wishlistItemId)
    {
        try
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var wishlistItem = _context.WishlistItems.FirstOrDefault(w => w.WishlistItemId == wishlistItemId && w.UserId == userId);

            if (wishlistItem != null)
            {
                _context.WishlistItems.Remove(wishlistItem);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            // Log the exception or handle it as appropriate for your application
            return BadRequest("An error occurred while processing your request.");
        }
    }

 
    private decimal GetUserBalance(string userId)
    {
        var user = _context.Users.FirstOrDefault(u => u.Id == userId);
        return user?.Balance ?? 0;
    }
}

Views/Shared/_Layout.cshtml
@using ExpenseTrack.Models.UserProfile
@{
    var userInfo = ViewData["UserInfo"] as UserInfo;
   
    string path = Context.Request.Path;

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseTracker</title>
    <script src="~/lib/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpenseTrack.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Tangerine">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <style>
        /* Custom styles */
        .active {
            position: relative; /* Set the positioning context for the pseudo-element */
            color: white !important; /* Override Bootstrap text color */
            border-radius: 5px; /* Optional: Add border-radius for rounded corners */
        }

            .active::after {
                content: ''; /* Create an empty content */
                position: absolute; /* Position the dot relative to its containing element */
                bottom: 0; /* Position the dot at the bottom of the link */
                left: 50%; /* Center the dot horizontally */
                transform: translateX(-50%); /* Adjust the horizontal centering */
                width: 90%; /* Set the width of the dot */
                height: 2px; /* Set the height of the dot */
                background-color: white; /* Set the color of the dot */
                 /* Create a circular shape */
            }


    </style>

</head>
<body style="font-family: 'Poppins', sans-serif; background: rgba(0, 0, 0, 0.2); background-image: url('/images/bgr1.jpeg');">
    <header>

        


        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom mb-3" style="background-color:#012A36">
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: white">
                     <img src="/images/logo1.png" alt="Logo" style="width: 40px; height: 38px;" class="d-inline-block mx-1 " /> 

               

                    Expense Tracker
                </a>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                        <!-- Center the content -->
                        <ul class="nav" >
                           
                            <li class="nav-item"  >
                                <a style=" color: white" class="nav-link  @(path.StartsWith("/Expense") ? "active" : "")" asp-area="" asp-controller="Expense" asp-action="Index">Expense</a>
                            </li>
                            <li class="nav-item  ">
                                <a style=" color: white" class="nav-link   @(path.StartsWith("/Wishlist") ? "active" : "")" asp-area="" asp-controller="Wishlist" asp-action="Index">Wish List</a>
                            </li>
                            <li class="nav-item ">
                                <a style=" color: white" class="nav-link   @(path.StartsWith("/UserProfile") ? "active" : "")" asp-area="" asp-controller="UserProfile" asp-action="Index">Profile</a>
                            </li>
                        </ul>
                    </div>
                }
                <partial name="_LoginPartial" />
            </div>

        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3 ">

            @RenderBody()
        </main>
    </div>
@* 
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ExpenseTrack - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

</body>
</html>

Views/Shared/_UserProfilePartial.cshtml
@using Microsoft.IdentityModel.Tokens;
@model ExpenseTrack.Models.UserProfile.UserProfileViewModel

@{
    ViewData["Title"] = "User Profile";
}

<div class="container-xl mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 class="text-center">User Profile</h2>

            <form asp-controller="UserProfile" asp-action="UpdateProfile" class="mt-4" method="post" enctype="multipart/form-data">

                <div class="text-center mb-3">
                    <a asp-area="" asp-controller="UserProfile" asp-action="Index">
                        <img src="@(!string.IsNullOrEmpty(Model.UserProfilePicture) ? Model.UserProfilePicture : "/images/default.jpg")" class="rounded-circle" style="width: 150px; height:150px; margin-bottom: 10px;" alt="Avatar" />
                    </a>
                    

                    <div>
                        <!-- Add Remove Picture button -->
                        @if (!string.IsNullOrEmpty(Model.UserProfilePicture) && Model.UserProfilePicture != "/images/default.jpg")
                        {
                            <button type="submit" name="RemovePicture" value="true" class="btn mb-2" style=" background-color:#7E5E86; color:white;"> Remove Picture</button>
                        }
                    </div>

                    <input type="file" class="form-control" name="PictureFile" accept=".jpg, .jpeg, .png">
                    @if (ViewData.ModelState["PictureFile"] != null)
                    {
                        <div class="text-danger">@ViewData.ModelState["PictureFile"].Errors.First().ErrorMessage</div>
                    }
                </div>


                <div class="form-group">
                    <label>Email</label>
                    <input type="text" class="form-control" value="@((Model != null && !string.IsNullOrEmpty(Model.Email)) ? Model.Email : string.Empty)" readonly>
                    <input type="hidden" name="Email" value="@Model.Email">
                </div>

                <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" name="FirstName" value="@((Model != null && !string.IsNullOrEmpty(Model.FirstName)) ? Model.FirstName : string.Empty)" required>
                </div>

                <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" name="LastName" value="@((Model != null && !string.IsNullOrEmpty(Model.LastName)) ? Model.LastName : string.Empty)" required>
                </div>

                <div class="form-group">
                    <label>Income</label>
                    <input type="number" class="form-control" name="Income" value="@((Model != null) ? Model.Income.ToString() : string.Empty)" min="1" pattern="\d+" title="Please enter a valid number" required>
                </div>
                <div class="form-group">
                    <label>Credit Date</label>
                    <select asp-for="CreditDate" class="form-control" required>
                        @for (int i = 1; i <= 28; i++)
                        {
                            @if(Model.CreditDate == i){
                                <option value="@i" selected>@i</option>               
                                }
                            else
                            {
                                <option value="@i">@i</option>
                            }


                        }
                    </select> 
                    </div>

                <div class="text-center mt-3">
                    <button type="submit" class="btn" style=" background-color:#013E50; color:white;">  Update Profile</button>
                </div>

            </form>
        </div>
    </div>
</div>


<script>
    // Log model values to the browser console
    console.log("Model.Email: ", "@Model.Email");
    console.log("Model.FirstName: ", "@Model.FirstName");
    console.log("Model.LastName: ", "@Model.LastName");
    console.log("Model.Income: ", "@Model.Income");
    console.log("Model.CreditDate: ", "@Model.CreditDate");
    console.log("Model.Status: ", status);
</script>